#!/usr/bin/env bash
# =============================================================================
# AmpAI Quick Setup Script
# =============================================================================
# Generates a .env file with secure random secrets so you can immediately run:
#   docker compose up -d --build
#
# Usage:
#   chmod +x setup.sh && ./setup.sh
#   docker compose up -d --build
# =============================================================================

set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists. Remove it first if you want to regenerate."
    echo "   To start: docker compose up -d --build"
    exit 0
fi

echo "🔧 Generating .env with secure random secrets..."

# Generate random secrets
generate_secret() {
    openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64
}

POSTGRES_PASSWORD=$(generate_secret | head -c 32)
JWT_SECRET=$(generate_secret)
ADMIN_PASSWORD="AmpAI-$(generate_secret | head -c 12)"

cat > "$ENV_FILE" << EOF
# =============================================================================
# AmpAI - Auto-generated environment file
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# Database
POSTGRES_DB=ampai
POSTGRES_USER=ampai
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_URL=redis://agent_redis:6379/0

# Authentication
JWT_SECRET=${JWT_SECRET}
AMPAI_DEFAULT_ADMIN_USERNAME=admin
AMPAI_DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Environment (change to "production" for production deployments)
AMPAI_ENV=development

# Ollama (local AI - optional, comment out if not using)
OLLAMA_BASE_URL=http://host.docker.internal:11434

# CORS
ALLOWED_ORIGINS=http://localhost:1420,http://127.0.0.1:1420,http://localhost:8000,http://localhost:8001,tauri://localhost

# Web Search (DuckDuckGo works without API key)
WEB_SEARCH_PROVIDER=duckduckgo

# Security - disabled by default
BROWSER_AUTOMATION_ENABLED=false
BROWSER_HEADLESS=false
TERMINAL_TOOLS_ENABLED=false
TERMINAL_REQUIRE_CONFIRMATION=true
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "📋 Your admin credentials:"
echo "   Username: admin"
echo "   Password: ${ADMIN_PASSWORD}"
echo ""
echo "🚀 Start AmpAI:"
echo "   docker compose up -d --build"
echo ""
echo "🌐 Access:"
echo "   API:  http://localhost:8000/docs"
echo "   Alt:  http://localhost:8001/docs"
echo ""
echo "📝 To stop:"
echo "   docker compose down"
echo ""
