from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field
from typing import Any, Dict, Optional, Protocol


class ProviderError(RuntimeError):
    pass


@dataclass
class ProviderBudget:
    max_tokens: int = 8_000
    max_cost_usd: float = 1.0
    timeout_seconds: float = 30.0
    max_retries: int = 2


@dataclass
class UsageMetadata:
    provider: str
    model: str
    job: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    latency_ms: int
    cost_estimate_usd: float
    operation: str
    created_at: float = field(default_factory=time.time)


class AIProvider(Protocol):
    name: str
    model: str

    def planEdits(self, prompt: str, repoContext: Dict[str, str], *, job_id: str) -> Dict[str, Any]: ...

    def generatePatch(self, fileContext: Dict[str, str], instruction: str, *, job_id: str) -> str: ...

    def summarizePR(self, changes: Dict[str, str], *, job_id: str) -> str: ...


class ProviderUsageLogger:
    def __init__(self, log_path: Optional[str] = None) -> None:
        self.log_path = log_path or os.getenv("AMPAI_PROVIDER_USAGE_LOG", "agent_data/provider_usage.jsonl")

    def write(self, entry: UsageMetadata) -> None:
        os.makedirs(os.path.dirname(self.log_path), exist_ok=True)
        with open(self.log_path, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry.__dict__) + "\n")


class BaseProvider:
    name = "base"

    def __init__(self, model: str, budget: Optional[ProviderBudget] = None, usage_logger: Optional[ProviderUsageLogger] = None) -> None:
        self.model = model
        self.budget = budget or ProviderBudget()
        self.usage_logger = usage_logger or ProviderUsageLogger()

    def _estimate_tokens(self, text: str) -> int:
        return max(1, len(text) // 4)

    def _estimate_cost(self, prompt_tokens: int, completion_tokens: int) -> float:
        return ((prompt_tokens + completion_tokens) / 1000.0) * 0.005

    def _guard_budget(self, prompt_tokens: int, completion_tokens: int) -> None:
        total = prompt_tokens + completion_tokens
        if total > self.budget.max_tokens:
            raise ProviderError(f"Token budget exceeded: {total} > {self.budget.max_tokens}")
        cost = self._estimate_cost(prompt_tokens, completion_tokens)
        if cost > self.budget.max_cost_usd:
            raise ProviderError(f"Estimated cost exceeded: ${cost:.4f} > ${self.budget.max_cost_usd:.4f}")

    def _record_usage(self, *, job_id: str, operation: str, prompt_tokens: int, completion_tokens: int, started_at: float) -> None:
        total = prompt_tokens + completion_tokens
        self.usage_logger.write(
            UsageMetadata(
                provider=self.name,
                model=self.model,
                job=job_id,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total,
                latency_ms=int((time.time() - started_at) * 1000),
                cost_estimate_usd=self._estimate_cost(prompt_tokens, completion_tokens),
                operation=operation,
            )
        )


class AmpAIProvider(BaseProvider):
    name = "ampai"

    def planEdits(self, prompt: str, repoContext: Dict[str, str], *, job_id: str) -> Dict[str, Any]:
        started = time.time()
        prompt_tokens = self._estimate_tokens(prompt) + sum(self._estimate_tokens(v) for v in repoContext.values())
        response = {
            "files_to_modify": sorted(repoContext.keys()),
            "rationale": "Generated by AmpAIProvider heuristic planning.",
            "summary": prompt[:160],
        }
        completion_tokens = self._estimate_tokens(json.dumps(response))
        self._guard_budget(prompt_tokens, completion_tokens)
        self._record_usage(job_id=job_id, operation="planEdits", prompt_tokens=prompt_tokens, completion_tokens=completion_tokens, started_at=started)
        return response

    def generatePatch(self, fileContext: Dict[str, str], instruction: str, *, job_id: str) -> str:
        started = time.time()
        prompt_tokens = self._estimate_tokens(instruction) + sum(self._estimate_tokens(v) for v in fileContext.values())
        patch = "\n".join(f"# {path}\n{content}" for path, content in fileContext.items())
        completion_tokens = self._estimate_tokens(patch)
        self._guard_budget(prompt_tokens, completion_tokens)
        self._record_usage(job_id=job_id, operation="generatePatch", prompt_tokens=prompt_tokens, completion_tokens=completion_tokens, started_at=started)
        return patch

    def summarizePR(self, changes: Dict[str, str], *, job_id: str) -> str:
        started = time.time()
        source = "\n".join(f"{k}: {len(v)} bytes" for k, v in changes.items())
        prompt_tokens = self._estimate_tokens(source)
        summary = f"Updated {len(changes)} file(s): {', '.join(sorted(changes.keys())[:8])}"
        completion_tokens = self._estimate_tokens(summary)
        self._guard_budget(prompt_tokens, completion_tokens)
        self._record_usage(job_id=job_id, operation="summarizePR", prompt_tokens=prompt_tokens, completion_tokens=completion_tokens, started_at=started)
        return summary


class OpenAIProvider(AmpAIProvider):
    name = "openai"


class AnthropicProvider(AmpAIProvider):
    name = "anthropic"


_PROVIDER_MAP = {
    "ampai": AmpAIProvider,
    "openai": OpenAIProvider,
    "anthropic": AnthropicProvider,
}


def resolve_provider(workspace_config: Optional[Dict[str, Any]] = None) -> AIProvider:
    workspace_config = workspace_config or {}
    provider_name = str(workspace_config.get("ai_provider") or os.getenv("AMPAI_AI_PROVIDER", "ampai")).lower()
    model_name = str(workspace_config.get("ai_model") or os.getenv("AMPAI_AI_MODEL", "ampai-default"))
    budget = ProviderBudget(
        max_tokens=int(workspace_config.get("ai_max_tokens", os.getenv("AMPAI_AI_MAX_TOKENS", 8000))),
        max_cost_usd=float(workspace_config.get("ai_max_cost_usd", os.getenv("AMPAI_AI_MAX_COST_USD", 1.0))),
        timeout_seconds=float(workspace_config.get("ai_timeout_seconds", os.getenv("AMPAI_AI_TIMEOUT_SECONDS", 30))),
        max_retries=int(workspace_config.get("ai_max_retries", os.getenv("AMPAI_AI_MAX_RETRIES", 2))),
    )
    cls = _PROVIDER_MAP.get(provider_name, AmpAIProvider)
    return cls(model=model_name, budget=budget)
